### ISSUE TITLE
Lỗi thiếu resources

### ISSUE THREAD

**Issue by ThaiDat** [hoainguyen33/DA_CK_NMKHDL#14]
![image](https://user-images.githubusercontent.com/18527312/104572730-9f1cc000-5686-11eb-8240-55eb13f5b177.png)

Khi chạy đến block 41 trong ảnh, chương trình sẽ báo lỗi thiếu resource.
Fix bằng thêm block 40 như trong ảnh

**Comment by templarassVN** [comment]
OKE!
